version: '3.9'

services:
  backend:
    image: nikkybalb0a/flask-backend:latest
    volumes:
      - backend-logs:/app/logs
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    ports:
      - "30000:5000"

  frontend:
    image: nikkybalb0a/frontend:latest
    volumes:
      - frontend-logs:/app/logs
    deploy:
      replicas: 1

  nginx:
    image: nikkybalb0a/custom-nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - nginx-logs:/var/log/nginx
    deploy:
      replicas: 1
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    deploy:
      replicas: 1
    networks:
      - monitoring
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    ports:
      - "9113:9113"
    command:
      - "-nginx.scrape-uri=http://nginx:80/stub_status"
    networks:
      - monitoring
    deploy:
      mode: replicated
      replicas: 1

volumes:
  backend-logs:
  frontend-logs:
  nginx-logs:
  grafana-storage:
  prometheus-data:

networks:
  monitoring:
    driver: overlay