version: '3.9'

services:
  backend1:
    container_name: backend1
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./logs/backend1:/app/logs

  backend2:
    container_name: backend2
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./logs/backend2:/app/logs

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./logs/frontend:/app/logs

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx