global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_backend'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']